export const LIST = {
  REQUEST : 'LIST_REQUEST',
  SUCCESS : 'LIST_SUCCESS',
  FAILURE : 'LIST_FAILURE'
}

export const OPEN_PORT = {
  REQUEST : 'OPEN_PORT_REQUEST',
  SUCCESS : 'OPEN_PORT_SUCCESS',
  FAILURE : 'OPEN_PORT_FAILURE'
}

export const READ = {
  REQUEST : 'READ_REQUEST',
  SUCCESS : 'READ_SUCCESS',
  FAILURE : 'READ_FAILURE'
}

export const SEND = {
  REQUEST : 'SEND_REQUEST',
  SUCCESS : 'SEND_SUCCESS',
  FAILURE : 'SEND_FAILURE'
}

export const SET_SEND_BUFFER = 'SET_SEND_BUFFER'

export const SET_PORT_CONFIG = 'SET_PORT_CONFIG'